# Generated by Django 4.1 on 2022-09-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_visualizer_delete_calculator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualizer',
            old_name='category',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='visualizer',
            old_name='title',
            new_name='product_category',
        ),
    ]
