# Generated by Django 4.1 on 2022-09-07 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title that briefly reflects the essence of the post', max_length=100)),
                ('content', models.TextField(help_text='Enter your text here')),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('date_of_origin', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes_dislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_dislike_status', models.BooleanField(null=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_post')),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter your date of birth', null=True)),
                ('short_bio', models.TextField(blank=True, help_text='Enter your short bio', max_length=1000, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Upload your profile avatar', null=True, upload_to='blog/images/avatars')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blogger info',
            },
        ),
        migrations.AddField(
            model_name='blog_post',
            name='like_dislikes',
            field=models.ManyToManyField(related_name='blog_post_mm', through='blog.Likes_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
