# Generated by Django 4.1 on 2022-08-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=50)),
                ('second_name', models.CharField(help_text='Enter your second name', max_length=50)),
                ('nickname', models.CharField(help_text='Enter unique nickname', max_length=50, unique=True)),
                ('e_mail', models.EmailField(help_text='Enter your e-mail. Each e-mail can be registred only one time', max_length=254, unique=True, verbose_name='E-mail')),
                ('date_of_bitrh', models.DateField(help_text='Enter your date of birth')),
                ('short_bio', models.TextField(help_text='Enter your short bio', max_length=1000)),
                ('avatar', models.ImageField(help_text='Upload your profile avatar', upload_to='')),
            ],
        ),
    ]
