# Generated by Django 4.1 on 2022-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload your profile avatar', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='date_of_bitrh',
            field=models.DateField(blank=True, help_text='Enter your date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter your first name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='second_name',
            field=models.CharField(blank=True, help_text='Enter your second name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='short_bio',
            field=models.TextField(blank=True, help_text='Enter your short bio', max_length=1000, null=True),
        ),
    ]
