# Generated by Django 4.1 on 2022-09-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_post_like_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='dislikes',
        ),
    ]
