# Generated by Django 4.1 on 2022-09-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes_dislikes',
            name='like_dislike',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (0, 'Nothing'), (1, 'Like')], default=0),
        ),
    ]
