# Generated by Django 4.1 on 2022-08-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogger_avatar_alter_blogger_date_of_bitrh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload your profile avatar', null=True, upload_to='blog/images/avatars'),
        ),
    ]
