# Generated by Django 4.1 on 2022-08-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogger_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
