# Generated by Django 4.1 on 2022-09-19 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_likes_dislikes_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes_dislikes',
            name='like_dislike',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (0, 'No reaction'), (1, 'Like')], default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter your comment here')),
                ('date_of_origin', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
