# Generated by Django 4.1 on 2022-08-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='date_of_origin',
            field=models.DateField(auto_now=True),
        ),
    ]
