# Generated by Django 4.1 on 2022-08-29 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_blog_post_date_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='second_name',
        ),
        migrations.AddField(
            model_name='blogger',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
