# Generated by Django 4.1 on 2022-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='date_of_origin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
