# Generated by Django 4.1 on 2022-08-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_post_date_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='date_of_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
