# Generated by Django 4.1 on 2022-08-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_post_date_of_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'verbose_name': 'Blogger info'},
        ),
    ]
