# Generated by Django 4.1 on 2022-09-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogger_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='date_of_bitrh',
            new_name='date_of_birth',
        ),
    ]
