# Generated by Django 4.1 on 2022-09-06 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_alter_blog_post_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post_mm', to=settings.AUTH_USER_MODEL),
        ),
    ]
